apiVersion: apps/v1
kind: Deployment
metadata: 
  name: spring-boot-app
  labels: 
    app: spring-boot-app
spec: 
  replicas: 2
  selector: 
    matchLabels:
      app: spring-boot-app
    template: 
      metadata:
        labels:
          apps: spring-boot-app
      spec: 
        containers:
        - name: spring-boot-app
          image: avian19/spring-docker:replaceImageTag
          ports:
          - containerPort: 8080